import type { Activity } from "@/types";

export const FALLBACK_TASKS: Activity[] = [
  {
    id: "activity-0",
    title: "Morning stretch",
    description: "Do a 5-minute morning stretch routine",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-1",
    title: "Hydrate with 2L water",
    description: "Drink at least 2 litres of water today",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-2",
    title: "Read 20 pages",
    description: "Read 20 pages of any book",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-3",
    title: "Cook a new recipe",
    description: "Try cooking a recipe you have never made before",
    isImageRequired: true,
    isTextRequired: false,
  },
  {
    id: "activity-4",
    title: "Declutter one drawer",
    description: "Pick one drawer and organize it",
    isImageRequired: true,
    isTextRequired: false,
  },
  {
    id: "activity-5",
    title: "Walk 8,000 steps",
    description: "Walk at least 8 000 steps during the day",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-6",
    title: "Call a friend",
    description: "Have a phone or video call with a friend",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-7",
    title: "Meditate for 10 min",
    description: "Sit and meditate for 10 minutes",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-8",
    title: "Journal gratitude",
    description: "Write down 3 things you are grateful for",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-9",
    title: "Try a new playlist",
    description: "Listen to a playlist you have never heard",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-10",
    title: "No-sugar afternoon",
    description: "Avoid any added sugar after lunch",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-11",
    title: "Sunset photo",
    description: "Take a photo of the sunset",
    isImageRequired: true,
    isTextRequired: false,
  },
  {
    id: "activity-12",
    title: "Plan tomorrow",
    description: "Write a plan for tomorrow before bed",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-13",
    title: "Learn one new word",
    description: "Learn and use a new word today",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-14",
    title: "Clean your desk",
    description: "Tidy up your workspace",
    isImageRequired: true,
    isTextRequired: false,
  },
  {
    id: "activity-15",
    title: "Do 20 squats",
    description: "Complete 20 bodyweight squats",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-16",
    title: "Screen-free hour",
    description: "Spend one hour without any screens",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-17",
    title: "Pack healthy lunch",
    description: "Prepare a healthy lunch for today",
    isImageRequired: true,
    isTextRequired: false,
  },
  {
    id: "activity-18",
    title: "Practice a hobby",
    description: "Spend at least 30 minutes on a hobby",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-19",
    title: "Do a random kindness",
    description: "Do something kind for someone unexpectedly",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-20",
    title: "Take a deep-breath break",
    description: "Take five deep breaths to reset",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-21",
    title: "Review your goals",
    description: "Review your weekly or monthly goals",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-22",
    title: "Make your bed",
    description: "Make your bed first thing in the morning",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-23",
    title: "Write a positive note",
    description: "Write a positive note to yourself or someone",
    isImageRequired: false,
    isTextRequired: false,
  },
  {
    id: "activity-24",
    title: "Dance to one song",
    description: "Pick a song and dance to it",
    isImageRequired: false,
    isTextRequired: false,
  },
];
